<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>scopeName</key>
    <string>source.pgn</string>
    <key>name</key>
    <string>Portable Game Notation</string>
    <key>fileTypes</key>
    <array>
      <string>pgn</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>end</key>
        <string>\]</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#required_tag_name</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#optional_tag_name</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#quoted_tag_value</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^((\{[^\}]*\})|[1-9]\d*\.)</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>comment.block.documentation.pgn</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(1-0|0-1|1\/2-1\/2|\*-\*)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.pgn</string>
          </dict>
        </dict>
        <key>name</key>
        <string>markup.bold.pgn</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#annotation</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>match</key>
        <string>^\s*(1-0|0-1|1\/2-1\/2|\*-\*)</string>
        <key>name</key>
        <string>markup.bold.pgn</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.pgn</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>match</key>
        <string>^\s*\S[^\n]+</string>
        <key>name</key>
        <string>comment.block.documentation.pgn</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>required_tag_name</key>
      <dict>
        <key>match</key>
        <string>\b(Event|Site|Date|Round|White|Black|Result)\b</string>
        <key>name</key>
        <string>keyword.control.pgn</string>
      </dict>
      <key>optional_tag_name</key>
      <dict>
        <key>match</key>
        <string>\b([A-Z][a-z]*)+\b</string>
        <key>name</key>
        <string>keyword.other.special-method.pgn</string>
      </dict>
      <key>quoted_tag_value</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.pgn</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.pgn</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.pgn</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character.escape.pgn</string>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>end</key>
        <string>\}</string>
        <key>name</key>
        <string>comment.block.documentation.pgn</string>
      </dict>
      <key>annotation</key>
      <dict>
        <key>match</key>
        <string>\$\d+</string>
        <key>name</key>
        <string>variable.other.pgn</string>
      </dict>
      <key>variation</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>end</key>
        <string>\)</string>
        <key>name</key>
        <string>markup.italic.pgn</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#variation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#annotation</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>